version: '3.7'
services:
  movie-watchlist:
    container_name: movie-watchlist
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    command: npm start
    ports:
      - '3000:3000'
