version: '3.7'
services:
  movie-watchlist:
    container_name: movie-watchlist
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/var/task'
      - '/var/task/node_modules'
    command: npm start
    ports:
      - '3000:3000'
    stdin_open: true
