export default {
    ADD_MOVIE_TO_WATCHLIST: "ADD_MOVIE_TO_WATCHLIST",
    REMOVE_MOVIE_FROM_WATCHLIST: "REMOVE_MOVIE_FROM_WATCHLIST",
    SORT_BY_DATE: "SORT_BY_DATE",
    SORT_BY_ALPHABETS: "SORT_BY_ALPHABETS",
    TIMEOUT_IN_SECONDS: 3000
}